name: Solidity tests
on:
    push:
        paths-ignore:
            - '**.md'
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - run: node --version
            - run: npm install
            - run: npm test
